### ISSUE TITLE
Camera FC on QVGA video resolution

### ISSUE THREAD

**Issue by zzottel** [ResurrectionRemix/frameworks_av#2]
I'm on ResurrectionRemix-M-v5.7.4-20161023-n7100, device GT-N7100, obviously.

When I go to the camera app, switch to video mode, and choose QVGA resolution, the app is force closed and will force close on every restart until I delete its app data.

I guess this is also the reason why I can't get video calls to work on apps like Riot or WhatsApp.

If there's any additional info I can provide to help fixing this problem, please tell me.

**Comment by fgl27** [comment]
way you ask here?
have you try the XDA thread is open and running and there is conversation about it there
http://forum.xda-developers.com/galaxy-note-2/development/rom-resurrection-remix-5-6-0-t3278709/page502

**Comment by zzottel** [comment]
Sorry for the late reply. Holidays. :-)

I had hoped to find a place here that makes more sense for reporting bugs than a > 500 pages single forum thread. But if that's not the correct place, I'll report it in the thread, too, of course, please just say so.

Please note that my bug is different from the camera freeze described often in that thread. (In fact, I haven't experienced that freeze anymore myself since I switched to Android 6.)

Steps to reproduce:
* Open camera app.
* Switch to video mode.
* Switch to QVGA resolution -> camera app will be force closed.
* Open camera app again -> immediate force close.
* Reboot, open camera app again -> immediate force close.
* Meanwhile, taking a photo from another app like WhatsApp still works.
* Trying to start a video call from apps like Riot or WhatsApp doesn't work (never, even when camera app is in a working state), no video on my side—my guess is that they are trying to use QVGA resolution, too.
* Deleting camera app's data makes it (camera app, not video calls) work again, as it then starts with another resolution again.
* All other video resolutions work.

As I said, if I should rather report this at the monster thread, please tell me, I'll do so.

**Comment by fgl27** [comment]
I already told you way do you insist posting thing here?
did anyone help you here? 
I'm  just trying help you but ou keep posting on the wrong place makes no sense...
if you had post there in XDA at least the person making the ROM would have noticed.
Not everyone has that device and probably RR developer team that makes the source don't have it so find the one making that ROM.

**Comment by zzottel** [comment]
Ok, will post there. :-/
